name: Fetch Contributors

on:
  pull_request: # This will run the workflow on pull request events
    types:
      - closed
  workflow_dispatch: # This will run the workflow on manual trigger

permissions:
  contents: write

jobs:
  contrib-readme-job:
    name: A job to fetch contributors list
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch contributors list
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          image_size: 100
          readme_path: "docs/contributors.md"
          collaborators: all
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Save contributors in assets
        if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
        run: |
          printf '%s\n' $(curl "https://api.github.com/repos/Mahmud0808/Iconify/contributors") > ./app/src/main/assets/Misc/contributors.json

      - name: Configure Git
        run: |
          git config --global user.name "Mahmud0808"
          git config --global user.email "crazymahmud08@gmail.com"

      - name: Stash changes
        run: |
          git stash --include-untracked

      - name: Pull latest changes from beta
        run: |
          git checkout beta
          git pull origin beta

      - name: Apply stashed changes
        run: |
          git stash pop

      - name: Commit changes and push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: 'beta'
          commit-message: 'Update contributors list'
          force-add: 'true'
          files: app/src/main/assets/Misc/contributors.json docs/contributors.md